# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'

    - name: Build-DB
      run: docker-compose -f ci_pipeline_githubactions/docker-compose.yml build

    - name: Create-DB
      run: docker-compose -f ci_pipeline_githubactions/docker-compose.yml up -d

    - name: Go Mod Init
      working-directory: ./ci_pipeline_githubactions
      run: go mod tidy

    - name: Test
      working-directory: ./ci_pipeline_githubactions
      run: go test -v main_test.go

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'

    - name: Build
      working-directory: ./ci_pipeline_githubactions
      run: go build -v main.go
